

// TOOL:     vlog2tf
// DATE:     Wed May 22 11:39:21 2013
 
// TITLE:    Lattice Semiconductor Corporation
// MODULE:   LFSR_Plus
// DESIGN:   LFSR_Plus
// FILENAME: LFSR_Plus_tf.v
// PROJECT:  Unknown
// VERSION:  2.0
// This file is auto generated by the Diamond


`timescale 1 ns/ 100 ps

// Define Module for Test Fixture
module LFSR_Plus_tf();

// Inputs
    reg clk;
    reg n_reset;
    reg enable;


// Outputs
    wire signed [15:0] g_noise_out;
    wire signed [15:0] u_noise_out;


// Bidirs


// Instantiate the UUT
// Please check and add your parameters manually
    LFSR_Plus UUT (
        .g_noise_out(g_noise_out), 
        .u_noise_out(u_noise_out), 
        .clk(clk), 
        .n_reset(n_reset), 
        .enable(enable)
        );


// Initialize Inputs
// You can add your stimulus here
	integer myfileUD, myfileGD, i;   // file handles
    initial 
	begin
            clk = 0;
            n_reset = 0;
            enable = 0;
			#200 n_reset = 1'b1;		// at time 200 release the reset			
			#250 enable = 1'b1;  		// at time 250 apply the enable		
			
			// Open a file for saving simulation data
			myfileUD = $fopen ("LFSR_test_file_UD.txt");
			myfileGD = $fopen ("LFSR_test_file_GD.txt");			
			// write to file
			for(i = 0; i < 16384; i = i+1) 
				begin
					#10 $fwrite (myfileUD, "%d \n", u_noise_out);
					#10 $fwrite (myfileGD, "%d \n", g_noise_out);
				end
    end

	always 
			#10 clk = ~clk;    // every ten nanoseconds invert the clock

endmodule // LFSR_Plus_tf


